### ISSUE TITLE
port to be set in DBDefs.pm is hardcoded to 5005 causing css issues

### ISSUE THREAD

**Issue by pagdot** [linuxserver/docker-musicbrainz#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The port in `DBDefs.pm` can't be changed using the [init-script](https://github.com/linuxserver/docker-musicbrainz/blob/master/root/etc/cont-init.d/20-brainzcode#L20). The domain can be set, but the port to use is hardcoded. This causes issues when used behind a reverse proxy or on a different port.

------------------------------

## Expected Behavior

Port can be set using an environmental variable

## Current Behavior

Port is set to 5005

## Steps to Reproduce

1. Create instance behind reverse proxy on a port different to 5005
2. Or bind instance to a port different to 5005 on the host.

## Environment (shouldn't matter though)
**OS:** Ubuntu 18.04
**CPU architecture:** x86_64
**How docker service was installed:** Using the [official instrucitons](https://docs.docker.com/engine/install/ubuntu/)

## Command used to create docker container (run/create/compose/screenshot)

```yaml
version: "3.4"


services:
  musicbrainz:
    image: linuxserver/musicbrainz
    container_name: musicbrainz
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: "Europe/Vienna"
      BRAINZCODE: redacted
      WEBADDRESS: mb.example.com
    volumes:
      - ./config:/config
    networks:
      - reverse-proxy

networks:
  default:
  reverse-proxy:
    external: true
```
