### ISSUE TITLE
Fails to run: 502 Bad Gateway

### ISSUE THREAD

**Issue by boredazfcuk** [linuxserver/docker-musicbrainz#82]
Hi,

I've fired up a brand new container, downloaded and imported a new Db, system says the Db is ready to accept connections, but nginx fails with 502 Bad Gateway.

## Expected Behavior
Musicbrainz to be accessible

## Current Behavior
Doesn't work. nginx reports 502 Bad Gateway

## Steps to Reproduce

1. Create new container
2. Start container
3. Wait until Db ready to accept connections message is displayed
4. Connect to server on port 5000

## Environment
**OS:** Debian Buster
**CPU architecture:** x86_64
**How docker service was installed:**

Docker repo added to apt

## Command used to create docker container (run/create/compose/screenshot)

```
   musicbrainz:
      hostname: musicbrainz
      networks:
         containers:
            aliases:
               - musicbrainz
      ports:
         - 5000:5000
      env_file:
         - timezone.env
         - musicbrainz.env
      image: linuxserver/musicbrainz
      healthcheck:
         test: wget --quiet --tries=1 --spider "http://musicbrainz:5000"&& psql -U abc --command "\c musicbrainz_db" || exit 1
         start_period: 30s
      restart: always
      volumes:
         - musicbrainz_config:/config
         - musicbrainz_data:/data
```

## Docker logs

https://pastebin.com/YSekN1RU
